backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "projects"
    label: "المشاريع"
    folder: "projects"
    create: true
    fields:
      - { label: "عنوان المشروع", name: "title", widget: "string" }
      - { label: "وصف العمل", name: "body", widget: "markdown" }
      
